### ISSUE TITLE
medic-conf --local fails in medic/config/standard

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#177]
Given webapp changes in https://github.com/medic/medic/pull/5508

Before deploying medic-conf to production, I ran ```node ~/conf/src/bin/medic-conf.js --local``` from folder `~/webapp/config/standard` and it works with no problems.

However, now after `npm publish` of the latest medic-conf branch, the command `medic-conf --local` in the same folder fails with an error from `minify-js`:

```
WARN Declaring s as function [0:191,4] 
WARN Declaring t as function [0:199,4] 
WARN Declaring u as function [0:205,4] 
ERROR Error: Warnings generated while minifying javscript.
    at module.exports.js (/usr/lib/node_modules/medic-conf/src/lib/minify-js.js:22:13)
    at module.exports.projectDir (/usr/lib/node_modules/medic-conf/src/lib/compile-contact-summary.js:53:10)
    at compileAppSettings (/usr/lib/node_modules/medic-conf/src/fn/compile-app-settings.js:67:24)
    at Promise.resolve.then (/usr/lib/node_modules/medic-conf/src/fn/compile-app-settings.js:44:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
```

**Comment by kennsippell** [comment]
Just published latest standard locally after installing v2.0.2.
