### ISSUE TITLE
Update medic-conf documentation with new syntax for command lines

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#182]
With https://github.com/medic/medic-conf/commit/95222da67d7b154cfeb48f8c7099fd8451bb85fe committed in medic-conf, there is a syntax change for all command lines. For example `medic-conf --url blah` becomes `medic-conf --url=blah`. 

Update documentation to reflect this change.

**Comment by kennsippell** [comment]
Interesting... 

For this command:
`~/webapp/config/standard$ medic-conf --url http://admin:pass@localhost:5984`

I see:
```
/usr/lib/node_modules/medic-conf/src/bin/medic-conf.js:103
  if(instanceUrl.match('/medic$')) {

TypeError: instanceUrl.match is not a function
    at Object.<anonymous> (/usr/lib/node_modules/medic-conf/src/bin/medic-conf.js:103:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by kennsippell** [comment]
Fixed
