### ISSUE TITLE
Declarative Configuration - appliesToType is not optional when appliesTo: contacts

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#208]
Given task:

```
{
  name: 'task',
  title: 'foo',
  actions: [ { form: 'example' } ],
  events: [ { days: 0, start: 0, end: 1 } ],
  appliesTo: 'contacts',
  appliesIf: function() { return true; },
  resolvedIf: function() { return false; },
}
```

Expected: AppliesToType is optional
Observed: 
```
     TypeError: Cannot read property 'indexOf' of undefined
      at eval (eval at evalString (test/run-lib.js:10:43), <anonymous>:89:44)
      at Object.evalString (test/run-lib.js:10:43)
      at evalInContext (test/run-lib.js:11:51)
      at runNoolsLib (test/run-lib.js:47:3)
      at Context.it (test/nools/lib.tasks.spec.js:336:29)
```

**Comment by newtewt** [comment]
Looks good.
