### ISSUE TITLE
Declarative Configuration - Global value user is not accessible from declarative configuration code

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#209]
The Declarative Configuration code has access to a global object `user` which provides details of the current logged in user. However, this value cannot be access due to jshint and eslint rules.

```
line 1136, col 28, 'user' is not defined. (W117)
line 1136, col 43, 'user' is not defined. (W117)
ERROR Error: jshint violations found in nools rules :¬(
    at module.exports (/home/kenn/conf/src/lib/jshint-with-report.js:36:11)
    at lint (/home/kenn/conf/src/lib/compile-nools-rules.js:10:3)
    at compileWithDefaultLayout (/home/kenn/conf/src/lib/compile-nools-rules.js:47:3)
    at module.exports.projectDir (/home/kenn/conf/src/lib/compile-nools-rules.js:112:12)
    at compileAppSettings (/home/kenn/conf/src/fn/compile-app-settings.js:68:14)
    at Promise.resolve.then (/home/kenn/conf/src/fn/compile-app-settings.js:44:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
``

**Comment by newtewt** [comment]
The user keyword is no longer blocked and available in declarative config.
