### ISSUE TITLE
upload-app-forms crashes when deploying projects/muso

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#278]
1. On a clean database
1. Navigate to projects/muso
1. `medic-conf --local`

Expected: Project Deploys
Observed: 

```
ERROR TypeError: Cannot read property 'includes' of undefined
    at promiseChain.then.then.then.then.catch.e (/home/kenn/conf/src/lib/upload-forms.js:65:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Regression from https://github.com/medic/medic-conf/commit/fbe488d0a4a07b0d086203df666056fb5d3eb0b8

**Comment by garethbowen** [comment]
Ready for AT on `278-remote-form-does-not-exist`

**Comment by garethbowen** [comment]
Starting AT on this.

**Comment by garethbowen** [comment]
LGTM.

On `master`:

```
WARN Error reading file: /home/gareth/src/medic/medic-projects/muso/.hashes/form:anc_followup.json 
ERROR TypeError: Cannot read property 'includes' of undefined
    at promiseChain.then.then.then.then.catch.e (/home/gareth/src/medic/medic-conf/src/lib/upload-forms.js:65:26)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

On the branch, no error, all actions complete.

**Comment by garethbowen** [comment]
Merged.
