### ISSUE TITLE
Error running csv-to-docs with null properties

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-conf#315]
Reproduce 
Run `medic-conf  [--url ] edit-contacts` in `cht-core/config/default` with this file.
[contact.zip](https://github.com/medic/medic-conf/files/4500754/contact.zip)

Error :
```
ERROR TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:192:18)
    at /Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:197:21
    at Array.map (<anonymous>)
    at toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:193:16)
    at /Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:197:21
    at Array.map (<anonymous>)
    at Object.toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:193:16)
    at saveJsonDoc (/Users/bede/Medic/steve-medic-conf/src/fn/edit-contacts.js:17:89)
    at Array.map (<anonymous>) 
```
Discovered while AT-ing #297 .
See @rosteve remarks here:
![image](https://user-images.githubusercontent.com/6979995/79705958-a1c2d280-830b-11ea-9581-801c4ee48f09.png)

**Comment by garethbowen** [comment]
We should definitely fix this but it's probably not a blocker because the workaround is to remove null properties. Scheduling for next release. Let me know if you disagree!

**Comment by garethbowen** [comment]
Ready for AT in `315-null-safe-stringify`

**Comment by ngaruko** [comment]
LGTM.
Back to you @garethbowen to merge!

**Comment by garethbowen** [comment]
Merged.
