### ISSUE TITLE
Error when using options

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#323]
With medic-conf 3.2.0 running on Windows I get the following error:
```
C:\Users\Marc\Downloads>medic-conf --url=https://medic:{password}@localhost upload-app-forms -- enroll --accept-self-signed-certs
INFO Processing config in Downloads.
INFO Actions:
     - upload-app-forms
INFO Starting action: upload-app-forms…
INFO Preparing form for upload: enroll.xml…
INFO No media directory found at C:\Users\Marc\Downloads/forms/app/enroll-media for form C:\Users\Marc\Downloads/forms/app/enroll.xml
ERROR Error: Unable to fetch xml attachment of doc with id form:enroll, returned status code = undefined
    at Object.preUploadForm (C:\Users\Marc\AppData\Roaming\npm\node_modules\medic-conf\src\lib\warn-upload-overwrite.js:186:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It works as expected by putting the options before the `-- <params>`
Eg. `medic-conf --url=https://medic:{password}@localhost upload-app-forms --accept-self-signed-certs -- enroll`

**Comment by garethbowen** [comment]
@abbyad The PR is merged. Is that sufficient to close this issue?

**Comment by abbyad** [comment]
Thanks, that should cover it!
