### ISSUE TITLE
Add an argument to accept all prompts. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#341]
When using medic-conf in scripts it can fail because there is no way to interact with the script. We should find a way to mimic other CLI tools by passing a `-y` arg or something to automatically accept prompts. 

```
stty: when specifying an output style, modes may not be set                                                                         /usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/read.sh: 
49: /usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/read.sh: cannot create /dev/tty: No such device or address                                                                
 stty: invalid argument ‘-f’                                                                                                         
Try 'stty --help' for more information.                                                                                             
ERROR Error: The current environment doesn't support interactive reading from TTY.                                                 
 stty: when specifying an output style, modes may not be set                                                                         /usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/read.sh: 49: /usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/read.sh: cannot create /dev/tty: No such device or address                                                                 stty: invalid argument ‘-f’                                                                                                         Try 'stty --help' for more information.                                                                                                 at readlineExt (/usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:221:19)                            at tryExt (/usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:258:15)                                 at /usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:363:15                                          at _readlineSync (/usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:433:5)                           at Object.exports.keyIn (/usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:901:17)                   at Object.exports.keyInSelect (/usr/lib/node_modules/medic-conf/node_modules/readline-sync/lib/readline-sync.js:1314:24)            at Object.preUploadDoc (/usr/lib/node_modules/medic-conf/src/lib/warn-upload-overwrite.js:143:26)                                   at process._tickCallback (internal/process/next_tick.js:68:7)     

```

**Comment by newtewt** [comment]
Closed as duplicate 

https://github.com/medic/medic-conf/issues/307
