### ISSUE TITLE
Need to install `request` manually

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#98]
Fresh install needed a manual install of `request`

```
$ medic-conf
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at /usr/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/usr/lib/node_modules/medic-conf/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/usr/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```

**Comment by alxndrsn** [comment]
Can you confirm which version of `medic-conf` you're seeing this for?  I can't recreate.

**Comment by jillrshah** [comment]
```
Jills-MacBook-Air:~ jill$ sudo npm install -g medic-conf
Password:
/usr/local/bin/pngout-medic -> /usr/local/lib/node_modules/medic-conf/bin/pngout
/usr/local/bin/medic-conf -> /usr/local/lib/node_modules/medic-conf/src/bin/medic-conf.js
/usr/local/bin/shell-completion-for-medic-conf -> /usr/local/lib/node_modules/medic-conf/src/bin/shell-completion.js
/usr/local/bin/medic-logs -> /usr/local/lib/node_modules/medic-conf/src/bin/medic-logs.bash

> phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/medic-conf/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [=======================-----------------] 57%
Received 16746K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/medic-conf/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1540221576357/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/medic-conf/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/local/lib/node_modules/medic-conf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules/medic-conf/node_modules/phantomjs-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ medic-conf@1.18.3
added 98 packages, removed 56 packages and updated 34 packages in 18.216s
```

**Comment by jillrshah** [comment]
Then the error: 
```
Jills-MacBook-Air:~ jill$ medic-conf
module.js:540
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/usr/local/lib/node_modules/medic-conf/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
Jills-MacBook-Air:~ jill$ medic-conf --version
module.js:540
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/usr/local/lib/node_modules/medic-conf/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/medic-conf/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
Jills-MacBook-Air:~ jill$ 

```

**Comment by abbyad** [comment]
(Resolved by doing `npm i -g request`)
